name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: dawidd6/action-publish-gem@master
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
