name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to RubyGems
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
      - name: Bump Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v2
        with:
          token: ${{secrets.GITHUB_API_TOKEN}}
          formula: dawidd6/homebrew-tap/actions-updater
          force: true
