name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - name: Build
        run: gem build *.gemspec
      - name: Install
        run: gem install *.gem
      - name: Run program
        run: |
          actions-updater
          actions-updater .github/workflows/*.yml
