name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6-alpine
    steps:
      - name: Make install
        run: make install
      - name: Run test
        run: ruby test.rb
      - name: Run main
        run: ruby main.rb
      - name: Run program
        run: actions-updater .github/workflows/*.yml