name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - run: gem install bundler
      - run: bundle install
      - run: rake
      - run: rake install
      - run: |
          docker build -t actions-updater .
          docker run -v $PWD:/app:ro actions-updater .github/workflows/*.yml
      - run: |
          actions-updater
          actions-updater --write .github/workflows/*.yml
