name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - name: Bundle
        run: bundle
      - name: Test
        run: rake
      - name: Install
        run: rake install
      - name: Run
        run: |
          actions-updater
          actions-updater .github/workflows/*.yml
